INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Winner", "Gaming", 100000, 12/1, 12/2);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("C", "lame", 2, 1/10, 4/2);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("d", "hi", 444, 4/1, 4/10);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("e", "eatting", 10555, 6/1, 7/2);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("sdf", "stand", 77, 8/1, 12/2);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("g", "goo", 94534, 12/1, 12/2);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("h", "hi", 324, 12/1, 12/2);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("i", "ice", 65555, 12/1, 12/2);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("w", "wow", 9888, 12/1, 12/2);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("r", "rotfl", 2728782, 12/1, 12/2);

INSERT INTO users (name, age) VALUES ("Mandy", 3);
INSERT INTO users (name, age) VALUES ("Cindy", 3);
INSERT INTO users (name, age) VALUES ("Bob", 3);
INSERT INTO users (name, age) VALUES ("Joe", 3);
INSERT INTO users (name, age) VALUES ("Lary", 3);
INSERT INTO users (name, age) VALUES ("Molly", 3);
INSERT INTO users (name, age) VALUES ("Mandy", 3);
INSERT INTO users (name, age) VALUES ("Mandy", 3);
INSERT INTO users (name, age) VALUES ("Mandy", 3);
INSERT INTO users (name, age) VALUES ("Mandy", 3);
INSERT INTO users (name, age) VALUES ("Herb", 3);
INSERT INTO users (name, age) VALUES ("Mandy", 3);
INSERT INTO users (name, age) VALUES ("Mandy", 3);
INSERT INTO users (name, age) VALUES ("Mandy", 3);
INSERT INTO users (name, age) VALUES ("Mandy", 3);
INSERT INTO users (name, age) VALUES ("Mandy", 3);
INSERT INTO users (name, age) VALUES ("Mandy", 3);
INSERT INTO users (name, age) VALUES ("Mandy", 3);
INSERT INTO users (name, age) VALUES ("Mandy", 3);
INSERT INTO users (name, age) VALUES ("Mandy", 3);


INSERT INTO pledges (amount, project_id, user_id) VALUES (2000, 1, 10);
INSERT INTO pledges (amount, project_id, user_id) VALUES (2000, 1, 10);
INSERT INTO pledges (amount, project_id, user_id) VALUES (2000, 1, 10);
INSERT INTO pledges (amount, project_id, user_id) VALUES (2000, 1, 10);
INSERT INTO pledges (amount, project_id, user_id) VALUES (2000, 1, 10);
INSERT INTO pledges (amount, project_id, user_id) VALUES (2000, 1, 10);
INSERT INTO pledges (amount, project_id, user_id) VALUES (2000, 1, 10);
INSERT INTO pledges (amount, project_id, user_id) VALUES (2000, 1, 10);
INSERT INTO pledges (amount, project_id, user_id) VALUES (2000, 1, 10);
INSERT INTO pledges (amount, project_id, user_id) VALUES (2000, 1, 10);
INSERT INTO pledges (amount, project_id, user_id) VALUES (2000, 1, 10);
INSERT INTO pledges (amount, project_id, user_id) VALUES (2000, 1, 10);
INSERT INTO pledges (amount, project_id, user_id) VALUES (2000, 1, 10);
INSERT INTO pledges (amount, project_id, user_id) VALUES (2000, 1, 10);
INSERT INTO pledges (amount, project_id, user_id) VALUES (2000, 1, 10);
INSERT INTO pledges (amount, project_id, user_id) VALUES (2000, 1, 10);
INSERT INTO pledges (amount, project_id, user_id) VALUES (2000, 1, 10);
INSERT INTO pledges (amount, project_id, user_id) VALUES (2000, 1, 10);
INSERT INTO pledges (amount, project_id, user_id) VALUES (2000, 1, 10);
INSERT INTO pledges (amount, project_id, user_id) VALUES (2000, 1, 10);
INSERT INTO pledges (amount, project_id, user_id) VALUES (2000, 1, 10);
INSERT INTO pledges (amount, project_id, user_id) VALUES (2000, 1, 10);
INSERT INTO pledges (amount, project_id, user_id) VALUES (2000, 1, 10);
INSERT INTO pledges (amount, project_id, user_id) VALUES (2000, 1, 10);
INSERT INTO pledges (amount, project_id, user_id) VALUES (2000, 1, 10);
INSERT INTO pledges (amount, project_id, user_id) VALUES (2000, 1, 10);
INSERT INTO pledges (amount, project_id, user_id) VALUES (2000, 1, 10);
INSERT INTO pledges (amount, project_id, user_id) VALUES (2000, 1, 10);
INSERT INTO pledges (amount, project_id, user_id) VALUES (2000, 1, 10);
INSERT INTO pledges (amount, project_id, user_id) VALUES (2000, 1, 10);
